### ISSUE TITLE
咨询，请问怎么修改显示位置。

### ISSUE THREAD

**Issue by agrichron** [duoani/obsidian-gtd#1]
您好，我目前也在使用dataview管理项目，但是有个问题，就是table显示的宽度不美观，所以想修改显示位置。

默认模式是在中间显示，而且有一定宽度。怎么修改成在最左侧显示？

我对比了一下主题样式，app设置，js脚本中都没有发现可修改的地方，所以请问是怎么实现的。

**Comment by agrichron** [comment]
呀 找到了，是这两个参数，在主题样式中。
`.markdown-source-view.is-readable-line-width ,`
`.markdown-preview-view.is-readable-line-width`

**Comment by duoani** [comment]
不太明白你的意思，如果你想问如何更改表格的对齐方式的话，可以了解一下CSS 对于table对齐的代码，如 text-align: left
